# Generated by Django 4.0.2 on 2022-02-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='solicitante',
            new_name='Solicitantes',
        ),
    ]
