# Generated by Django 4.0.2 on 2022-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='cor',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
